export const CONSTANT = {
    GAME_WIDTH: 800,
    GAME_HEIGHT: 500,
    GROUND_Y: 420,
    GRAVITY: 0.8,
    JUMP_FORCE: -15,
    MOVE_SPEED: 4,
    FIGHTER_WIDTH: 80,
    FIGHTER_HEIGHT: 120,
    MAX_HEALTH: 100,
    ROUND_TIME: 99,
    HIT_COOLDOWN: 500
}